import {BedrockRuntimeClient,ConverseCommand} from '@aws-sdk/client-bedrock-runtime';
import type {Advice,Crop,Language} from '../shared/types'; import {CONFIG} from '../shared/config';
export interface AIService { advice(crop:Crop,acres:number,district:string,month:number,language:Language):Promise<Advice> }
export class MockAI implements AIService { async advice(crop:Crop,acres:number,district:string,month:number,language:Language):Promise<Advice>{const estimatedTonnes=Number((acres*CONFIG.tonnesPerAcre[crop]).toFixed(1));const tips={en:`Arrange collection in ${district} before the residue dries out.`,hi:`${district} में अवशेष सूखने से पहले उठान की व्यवस्था करें।`,pa:`${district} ਵਿੱਚ ਪਰਾਲੀ ਸੁੱਕਣ ਤੋਂ ਪਹਿਲਾਂ ਚੁਕਾਈ ਦਾ ਪ੍ਰਬੰਧ ਕਰੋ।`};return {estimatedTonnes,bestUses:crop==='paddy'?['Biomass pellets','Bio-CNG feedstock']:['Cattle fodder','Compost'],tip:tips[language]??tips.en};}}
const bedrock=new BedrockRuntimeClient({region:process.env.AWS_REGION??process.env.AWS_DEFAULT_REGION??'us-east-1'});
function parseAdvice(text:string):Advice|null{try{const cleaned=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');let parsed:any;try{parsed=JSON.parse(cleaned);}catch{const start=cleaned.indexOf('{'),end=cleaned.lastIndexOf('}');if(start<0||end<=start)return null;parsed=JSON.parse(cleaned.slice(start,end+1));}if(!Number.isFinite(parsed?.estimatedTonnes)||parsed.estimatedTonnes<0||!Array.isArray(parsed.bestUses)||parsed.bestUses.length!==2||!parsed.bestUses.every((x:unknown)=>typeof x==='string'&&x.trim())||typeof parsed.tip!=='string'||!parsed.tip.trim())return null;return {estimatedTonnes:parsed.estimatedTonnes,bestUses:parsed.bestUses.map((x:string)=>x.trim()),tip:parsed.tip.trim()};}catch{return null;}}
export class BedrockAI implements AIService {
 constructor(private modelId=process.env.BEDROCK_MODEL_ID??''){}
 async advice(crop:Crop,acres:number,district:string,month:number,language:Language):Promise<Advice>{const fallback=await new MockAI().advice(crop,acres,district,month,language);if(!this.modelId)return fallback;try{const response=await bedrock.send(new ConverseCommand({modelId:this.modelId,system:[{text:'You provide concise crop-residue reuse advice. Return only one valid JSON object without markdown. Do not add any keys.'}],messages:[{role:'user',content:[{text:`Given crop=${crop}, farm area=${acres} acres, district=${district}, current month=${month}, requested language=${language}, estimate the residue tonnes and offer two practical uses plus one short seasonal tip in the requested language. Return exactly this JSON shape: {"estimatedTonnes": number, "bestUses": ["string", "string"], "tip": "string"}. Use approximate quantity factors: paddy 2.0 tonnes per acre; wheat 1.6 tonnes per acre.`}]}],inferenceConfig:{maxTokens:300,temperature:0.2}}));const text=response.output?.message?.content?.flatMap(c=>'text'in c?[c.text]:[]).join('\n')??'';return parseAdvice(text)??fallback;}catch{return fallback;}}
}
export const ai:AIService=process.env.USE_AWS==='true'?new BedrockAI():new MockAI();

