import {DynamoDBClient} from '@aws-sdk/client-dynamodb';
import {BatchWriteCommand,DeleteCommand,DynamoDBDocumentClient,GetCommand,PutCommand,QueryCommand,ScanCommand,TransactWriteCommand,UpdateCommand} from '@aws-sdk/lib-dynamodb';
import type {Repository} from '../backend/repository';
import type {Account,ApprovalRecord,Demand,Listing,Match,Session,User} from '../shared/types';
import {seedDemands,seedListings,seedMatches} from '../shared/seed';
import {seedAccounts,makeAccount,newAccount} from '../backend/auth';
import {createHash,timingSafeEqual} from 'node:crypto';

const names={users:process.env.DYNAMO_USERS_TABLE??'KhetLoopUsers',listings:process.env.DYNAMO_LISTINGS_TABLE??'KhetLoopListings',demands:process.env.DYNAMO_DEMANDS_TABLE??'KhetLoopDemands',matches:process.env.DYNAMO_MATCHES_TABLE??'KhetLoopMatches'};
const client=DynamoDBDocumentClient.from(new DynamoDBClient({region:process.env.AWS_REGION??process.env.AWS_DEFAULT_REGION??'us-east-1'}),{marshallOptions:{removeUndefinedValues:true}});
const chunks=<T,>(items:T[],size:number)=>Array.from({length:Math.ceil(items.length/size)},(_,i)=>items.slice(i*size,(i+1)*size));
const accountRow=(a:Account)=>({...a.user,kind:'account',passwordHash:a.passwordHash,approved:a.approved,approvalStatus:a.approved?'APPROVED':'PENDING',...(a.approvedAt?{approvedAt:a.approvedAt}:{}),...(a.approvedBy?{approvedBy:a.approvedBy}:{})});
const accountFrom=(x:any):Account=>{const {passwordHash,approved,approvalStatus,kind,approvedAt,approvedBy,...user}=x;return {user:user as User,passwordHash,approved:approved===true,...(approvedAt?{approvedAt}:{}),...(approvedBy?{approvedBy}:{})};};
export class DynamoStore implements Repository {
 private async scan<T>(tableName:string):Promise<T[]>{const Items:T[]=[];let ExclusiveStartKey:any;do{const out=await client.send(new ScanCommand({TableName:tableName,ExclusiveStartKey}));Items.push(...(out.Items as T[]??[]));ExclusiveStartKey=out.LastEvaluatedKey;}while(ExclusiveStartKey);return Items;}
 private async getAccount(id:string){const out=await client.send(new GetCommand({TableName:names.users,Key:{id}}));return out.Item?.kind==='account'?accountFrom(out.Item):null;}
 private async getByPhone(phone:string){const out=await client.send(new QueryCommand({TableName:names.users,IndexName:'PhoneIndex',KeyConditionExpression:'#phone = :phone',ExpressionAttributeNames:{'#phone':'phone'},ExpressionAttributeValues:{':phone':phone},Limit:1}));const row=out.Items?.[0];return row?.kind==='account'?accountFrom(row):null;}
 async listings(){return this.scan<Listing>(names.listings);} async demands(){return this.scan<Demand>(names.demands);} async matches(){return this.scan<Match>(names.matches);}
 async users(){return (await this.scan<any>(names.users)).filter(x=>x.kind==='account').map(x=>accountFrom(x).user);}
 async addListing(x:Listing){await client.send(new PutCommand({TableName:names.listings,Item:x}));} async addDemand(x:Demand){await client.send(new PutCommand({TableName:names.demands,Item:x}));} async addMatch(x:Match){await client.send(new PutCommand({TableName:names.matches,Item:x}));}
 private async update<T extends {id:string}>(tableName:string,id:string,patch:Partial<T>):Promise<T|null>{const entries=Object.entries(patch).filter(([k,v])=>k!=='id'&&v!==undefined);if(!entries.length)return null;const namesMap:Record<string,string>={},values:Record<string,unknown>={};const sets=entries.map(([k,v],i)=>{namesMap[`#k${i}`]=k;values[`:v${i}`]=v;return `#k${i} = :v${i}`;});try{const out=await client.send(new UpdateCommand({TableName:tableName,Key:{id},UpdateExpression:`SET ${sets.join(', ')}`,ExpressionAttributeNames:namesMap,ExpressionAttributeValues:values,ReturnValues:'ALL_NEW'}));return out.Attributes as T??null;}catch(e:any){if(e.name==='ConditionalCheckFailedException')return null;throw e;}}
 async updateMatch(id:string,patch:Partial<Match>){return this.update<Match>(names.matches,id,patch);} async updateListing(id:string,patch:Partial<Listing>){await this.update<Listing>(names.listings,id,patch);}
 async updateProfile(id:string,patch:{name:string;phone:string;village:string}){const account=await this.getAccount(id);if(!account)return {error:'not_found'} as const;if(patch.phone!==account.user.phone){const existing=await this.getByPhone(patch.phone);if(existing&&existing.user.id!==id)return {error:'phone_taken'} as const;}try{const out=await client.send(new UpdateCommand({TableName:names.users,Key:{id},UpdateExpression:'SET #name = :name, #phone = :phone, #village = :village',ConditionExpression:'#kind = :account',ExpressionAttributeNames:{'#name':'name','#phone':'phone','#village':'village','#kind':'kind'},ExpressionAttributeValues:{':name':patch.name,':phone':patch.phone,':village':patch.village,':account':'account'},ReturnValues:'ALL_NEW'}));return {user:accountFrom(out.Attributes).user} as const;}catch(error:any){if(error.name==='ConditionalCheckFailedException')return {error:'not_found'} as const;throw error;}}
 async changePassword(id:string,current:string,next:string,sessionToken:string){const account=await this.getAccount(id);if(!account)return 'not_found' as const;if(!makeAccount.verify(current,account.passwordHash))return 'invalid' as const;const oldHash=account.passwordHash;account.passwordHash=makeAccount.create(account.user,next).passwordHash;try{await client.send(new PutCommand({TableName:names.users,Item:accountRow(account),ConditionExpression:'passwordHash = :oldHash AND #kind = :account',ExpressionAttributeNames:{'#kind':'kind'},ExpressionAttributeValues:{':oldHash':oldHash,':account':'account'}}));}catch(error:any){if(error.name==='ConditionalCheckFailedException')return 'invalid' as const;throw error;}const sessions=await this.scan<any>(names.users);for(const row of sessions.filter(x=>x.kind==='session'&&x.userId===id&&x.id!==`SESSION#${sessionToken}`))await client.send(new DeleteCommand({TableName:names.users,Key:{id:row.id}}));return 'ok' as const;}
 async requestPasswordReset(phone:string){const account=await this.getByPhone(phone);if(!account||account.user.role==='admin')return;const now=Math.floor(Date.now()/1000),rows=await this.scan<any>(names.users);if(rows.some(row=>row.kind==='passwordReset'&&row.userId===account.user.id&&row.status!=='USED'&&(row.expiresAt??0)>now))return;const id=crypto.randomUUID();await client.send(new PutCommand({TableName:names.users,Item:{id:`RESET#${id}`,kind:'passwordReset',userId:account.user.id,requestedAt:new Date().toISOString(),status:'PENDING',expiresAt:now+24*60*60},ConditionExpression:'attribute_not_exists(id)'}));}
 async passwordResetRequests(){const now=Math.floor(Date.now()/1000),rows=await this.scan<any>(names.users),requests=rows.filter(row=>row.kind==='passwordReset'&&row.status!=='USED'&&(row.expiresAt??0)>now);return (await Promise.all(requests.map(async row=>{const account=await this.getAccount(row.userId);return account?{id:String(row.id).replace(/^RESET#/,''),userId:row.userId,userName:account.user.name,phone:account.user.phone,requestedAt:row.requestedAt,status:row.status==='ISSUED'?'issued' as const:'pending' as const,expiresAt:row.status==='ISSUED'?row.expiresAt:undefined}:null;}))).filter((row):row is NonNullable<typeof row>=>Boolean(row)).sort((a,b)=>b.requestedAt.localeCompare(a.requestedAt));}
 async issuePasswordReset(id:string,adminId:string){const requestId=`RESET#${id}`,out=await client.send(new GetCommand({TableName:names.users,Key:{id:requestId}})),request=out.Item;if(request?.kind!=='passwordReset'||request.status==='USED'||(request.expiresAt??0)<=Math.floor(Date.now()/1000))return null;const account=await this.getAccount(request.userId);if(!account||account.user.role==='admin')return null;const code=crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase(),codeHash=createHash('sha256').update(code).digest('hex');try{await client.send(new UpdateCommand({TableName:names.users,Key:{id:requestId},UpdateExpression:'SET #status = :issued, issuedBy = :admin, issuedAt = :at, expiresAt = :expires, codeHash = :hash, attempts = :zero',ConditionExpression:'#kind = :kind AND #status <> :used',ExpressionAttributeNames:{'#status':'status','#kind':'kind'},ExpressionAttributeValues:{':issued':'ISSUED',':admin':adminId,':at':new Date().toISOString(),':expires':Math.floor(Date.now()/1000)+15*60,':hash':codeHash,':zero':0,':kind':'passwordReset',':used':'USED'}}));return code;}catch(error:any){if(error.name==='ConditionalCheckFailedException')return null;throw error;}}
 async completePasswordReset(phone:string,code:string,password:string){const account=await this.getByPhone(phone);if(!account||account.user.role==='admin')return false;const rows=await this.scan<any>(names.users),now=Math.floor(Date.now()/1000),request=rows.find(row=>row.kind==='passwordReset'&&row.userId===account.user.id&&row.status==='ISSUED'&&row.expiresAt>now);if(!request||(request.attempts??0)>=5||!request.codeHash)return false;const codeHash=createHash('sha256').update(code).digest('hex');if(!timingSafeEqual(Buffer.from(request.codeHash,'hex'),Buffer.from(codeHash,'hex'))){try{await client.send(new UpdateCommand({TableName:names.users,Key:{id:request.id},UpdateExpression:'ADD attempts :one',ConditionExpression:'#status = :issued AND expiresAt > :now AND (attribute_not_exists(attempts) OR attempts < :max)',ExpressionAttributeNames:{'#status':'status'},ExpressionAttributeValues:{':one':1,':issued':'ISSUED',':now':now,':max':5}}));}catch{}return false;}const oldHash=account.passwordHash;account.passwordHash=makeAccount.create(account.user,password).passwordHash;try{await client.send(new TransactWriteCommand({TransactItems:[{Put:{TableName:names.users,Item:accountRow(account),ConditionExpression:'passwordHash = :oldHash AND #kind = :account',ExpressionAttributeNames:{'#kind':'kind'},ExpressionAttributeValues:{':oldHash':oldHash,':account':'account'}}},{Update:{TableName:names.users,Key:{id:request.id},UpdateExpression:'SET #status = :used REMOVE codeHash',ConditionExpression:'#status = :issued AND codeHash = :hash AND expiresAt > :now AND (attribute_not_exists(attempts) OR attempts < :max)',ExpressionAttributeNames:{'#status':'status'},ExpressionAttributeValues:{':used':'USED',':issued':'ISSUED',':hash':codeHash,':now':now,':max':5}}}]}));}catch(error:any){if(error.name==='TransactionCanceledException'||error.name==='ConditionalCheckFailedException')return false;throw error;}const sessions=rows.filter(row=>row.kind==='session'&&row.userId===account.user.id);for(const row of sessions)await client.send(new DeleteCommand({TableName:names.users,Key:{id:row.id}}));return true;}
 async login(phone:string,password:string){const a=await this.getByPhone(phone);if(!a||!makeAccount.verify(password,a.passwordHash))return null;return {user:a.user,approved:a.approved};}
 async register(input:{role:'farmer'|'buyer';name:string;phone:string;password:string;district:string}){if(await this.getByPhone(input.phone))return null;const a=newAccount(input.role,input.name,input.phone,input.password,input.district);await client.send(new PutCommand({TableName:names.users,Item:accountRow(a),ConditionExpression:'attribute_not_exists(id)'}));return a;}
 async pendingCompanies(){const out=await client.send(new QueryCommand({TableName:names.users,IndexName:'RoleApprovalIndex',KeyConditionExpression:'#role = :role AND approvalStatus = :status',ExpressionAttributeNames:{'#role':'role'},ExpressionAttributeValues:{':role':'buyer',':status':'PENDING'}}));return (out.Items??[]).filter(x=>x.kind==='account').map(x=>accountFrom(x).user);}
 async approvalHistory():Promise<ApprovalRecord[]>{return (await this.scan<any>(names.users)).filter(x=>x.kind==='account'&&x.role==='buyer'&&x.approved===true).map(x=>{const a=accountFrom(x);return {user:a.user,approvedAt:a.approvedAt,approvedBy:a.approvedBy};}).sort((a,b)=>(b.approvedAt??'').localeCompare(a.approvedAt??''));}
 async approveCompany(id:string,approverId:string){try{await client.send(new UpdateCommand({TableName:names.users,Key:{id},UpdateExpression:'SET approved = :yes, approvalStatus = :status, approvedAt = :at, approvedBy = :by',ConditionExpression:'#role = :buyer AND kind = :account AND approvalStatus = :pending',ExpressionAttributeNames:{'#role':'role'},ExpressionAttributeValues:{':yes':true,':status':'APPROVED',':buyer':'buyer',':account':'account',':pending':'PENDING',':at':new Date().toISOString(),':by':approverId}}));return true;}catch(e:any){if(e.name==='ConditionalCheckFailedException')return false;throw e;}}
 async resetAdminPassword(phone:string,password:string){const account=await this.getByPhone(phone);if(!account||account.user.role!=='admin')return false;account.passwordHash=makeAccount.create(account.user,password).passwordHash;await client.send(new PutCommand({TableName:names.users,Item:accountRow(account)}));const sessions=await this.scan<any>(names.users);for(const row of sessions.filter(x=>x.kind==='session'&&x.userId===account.user.id))await client.send(new DeleteCommand({TableName:names.users,Key:{id:row.id}}));return true;}
 async createSession(userId:string){const token=crypto.randomUUID()+crypto.randomUUID(),expiresAt=Math.floor(Date.now()/1000)+7*24*60*60;await client.send(new PutCommand({TableName:names.users,Item:{id:`SESSION#${token}`,kind:'session',userId,expiresAt}}));return token;}
 async session(token:string){const out=await client.send(new GetCommand({TableName:names.users,Key:{id:`SESSION#${token}`}})),row=out.Item;if(!row||row.expiresAt<=Math.floor(Date.now()/1000))return null;return (await this.getAccount(row.userId))?.user??null;}
 async logout(token:string){await client.send(new DeleteCommand({TableName:names.users,Key:{id:`SESSION#${token}`}}));}
 private async replaceTable(tableName:string,rows:Record<string,unknown>[]){const old=await this.scan<{id:string}>(tableName);for(const batch of chunks(old.map(x=>({DeleteRequest:{Key:{id:x.id}}})),25))await client.send(new BatchWriteCommand({RequestItems:{[tableName]:batch}}));for(const batch of chunks(rows.map(Item=>({PutRequest:{Item}})),25))await client.send(new BatchWriteCommand({RequestItems:{[tableName]:batch}}));}
 async seedDemoData(){const retry=async(tableName:string,requests:any[])=>{let pending=requests;for(let attempt=0;pending.length&&attempt<8;attempt++){const out=await client.send(new BatchWriteCommand({RequestItems:{[tableName]:pending}}));pending=out.UnprocessedItems?.[tableName]??[];if(pending.length)await new Promise(r=>setTimeout(r,100*2**attempt));}if(pending.length)throw new Error(`Unprocessed writes remain for ${tableName}`);};for(const a of seedAccounts())await client.send(new PutCommand({TableName:names.users,Item:accountRow(a)}));for(const [table,rows] of [[names.listings,seedListings],[names.demands,seedDemands],[names.matches,seedMatches]] as const)for(const batch of chunks(rows.map(Item=>({PutRequest:{Item}})),25))await retry(table,batch);}
 async reset(){await this.replaceTable(names.listings,seedListings);await this.replaceTable(names.demands,seedDemands);await this.replaceTable(names.matches,seedMatches);}
}

